### ISSUE TITLE
Multiple bug with the 2FA

### ISSUE THREAD

**Issue by Blu-ea** [BenJ3D/ft_transcendence#250]
je ne peux pas activer code pour 2FA 

Lorsque je recupere le code, le rentrer j ai un retour que le code est imvalide 
![image](https://github.com/BenJ3D/ft_transcendence/assets/82770859/66d2b6b2-3b99-40af-a8b3-956f5c3fa91e)

A un moment ca a fonctionner, mais impossible de ce connecter sur le compte avec le 2fa de rentrer

puis j ai essayer de me connecter avec 42 mais ne fonctionner pas temps que je n avais rien mis dans la case `2fa` (quelle que chose comme `asd` fonction)

**Comment by BenJ3D** [comment]
Aucun soucis sur les DELL en mode prod
